# Site settings
email: 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Leomiassi
description: 
url: ""
twitter_username:  
default_img: 

# Profile settings
name: Leonardo Miassi Netto
profile_img: /Images/lenha.jpg
profile: Computer Science student at University of São Paulo.
social:
  github: "https://github.com/leomiassi"
  instagram: "https://instagram.com/leomiassi"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]

theme: jekyll-theme-cayman
